// Autogenerated by Lokus
export const LokusDictionary = {
	type: "dictionary",
	baseLanguage: "en",
	timestamp: 1748767980201,
	base: {
		"landing.title": "Lokus — universal translation software",
		"landing.description": "Lokus is a universal localization format and a set of powerful tools designed to simplify and speed up the translation of various applications. It enables collaborative translation into multiple languages at once and integrates seamlessly into modern development workflows.",
		"landing.cta-button": "Get started",
		"editor.title": "Lokus Editor",
		"editor.nav.home": "Home",
		"editor.invalid-file": "Invalid file",
		"editor.invalid-file-message": "Invalid file format. Please upload a valid lokus file.",
		"editor.base-language": "Base language",
		"editor.last-change": "Last change",
		"editor.select-language": "Select language to translate",
		"editor.write-3": "Write translations to third column",
		"editor.download-dictionary": "Download new dictionary",
		"editor.download-translate": "Download translation only",
		"editor.modify-dictionary": "Add new record using bottom form or delete existing with button in third column",
	},
	dictionaries: {
		"ru": {
			"landing.title": "Lokus — универсальное программное обеспечение для перевода",
			"landing.description": "Lokus — это универсальный формат локализации и набор мощных инструментов, предназначенных для упрощения и ускорения перевода различных приложений. Он позволяет совместно переводить на несколько языков одновременно и бесшовно интегрируется в современные рабочие процессы разработки.",
			"landing.cta-button": "Начать",
			"editor.title": "Редактор Lokus",
			"editor.nav.home": "Главная",
			"editor.invalid-file": "Неверный файл",
			"editor.invalid-file-message": "Неверный формат файла. Пожалуйста, загрузите корректный файл lokus.",
			"editor.base-language": "Базовый язык",
			"editor.last-change": "Последнее изменение",
			"editor.select-language": "Выберите язык для перевода",
			"editor.write-3": "Запишите переводы в третий столбец",
			"editor.download-dictionary": "Скачать новый словарь",
			"editor.download-translate": "Скачать только перевод",
			"editor.modify-dictionary": "Добавите новую запись используя форму ниже или удалите существующую используя кнопку в 3 колонке",
		},
		"uk": {
			"landing.title": "Lokus — універсальне програмне забезпечення для перекладу",
			"landing.description": "Lokus — це універсальний формат локалізації та набір потужних інструментів, призначених для спрощення та прискорення перекладу різних додатків. Він дозволяє спільно перекладати на кілька мов одночасно та безшовно інтегрується в сучасні робочі процеси розробки.",
			"landing.cta-button": "Почати",
			"editor.title": "Редактор Lokus",
			"editor.nav.home": "Головна",
			"editor.invalid-file": "Неправильний файл",
			"editor.invalid-file-message": "Неправильний формат файлу. Будь ласка, завантажте коректний файл lokus.",
			"editor.base-language": "Базова мова",
			"editor.last-change": "Остання зміна",
			"editor.select-language": "Виберіть мову для перекладу",
			"editor.write-3": "Запишіть переклади в третій стовпець",
			"editor.download-dictionary": "Завантажити новий словник",
			"editor.download-translate": "Завантажити лише переклад",
			"editor.modify-dictionary": "Додайте новий запис використовуючи форму внизу або видаліть існуючий кнопкою в третьому стовпчику",
		},
	},
} as const;

	
export type LokusDictionaryType = Record<
	keyof typeof LokusDictionary.base,
	string
>;

export type LokusLanguageType =
	| keyof typeof LokusDictionary.dictionaries
	| typeof LokusDictionary.baseLanguage;

export function getLokusLanguage(lang?: string): LokusLanguageType {
	if (!lang) return LokusDictionary.baseLanguage;
	if (lang in LokusDictionary.dictionaries) {
		return lang as keyof typeof LokusDictionary.dictionaries;
	}
	return LokusDictionary.baseLanguage;
}

export function getLokusDictionary(
	language: LokusLanguageType,
): LokusDictionaryType {
	if (language === LokusDictionary.baseLanguage) return LokusDictionary.base;
	return {
		...LokusDictionary.base,
		...LokusDictionary.dictionaries[language],
	};
}